### ISSUE TITLE
Error on logout

### ISSUE THREAD

**Issue by develoQ** [XRPL-Labs/Xumm-Universal-SDK#7]
The following error occurred during logout.

```
index.js:450 Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'jwtCredential')
    at index.js:450:22
    at Generator.next (<anonymous>)
    at index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (index.js:4:12)
    at logout (index.js:445:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
```

Reproduction
https://github.com/develoQ/XummSDK-React-Demo/tree/logout-issue

**Comment by WietseWind** [comment]
That makes sense; if you call directly to `xumm.logout` in a React event, the `this` context does not exist: it's called as an anonymous function instead of as a member of the class.

If you change the button to this:
```html
<button onClick={logout}>Sign Out</button>
```

... And you define the local `logout` method like this:

```javascript
  const logout = () => {
    xumm.logout()
    setAccount('')
  }
```

... it works.
